// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akmfvpwxchjosyismpss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbWZ2cHd4Y2hqb3N5aXNtcHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTkzOTAsImV4cCI6MjA2Nzg5NTM5MH0.SoTWXcMvxofxkTXtNC3Y-pJy9PzgRphpKAZzUWwxJB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});